project:
  type: website

website:
  page-navigation: true
  title: "Atlantis Model for Puget Sound"
  site-url: "https://hmorzaria.github.io/psatlantismodelupdates/"
  repo-url: "https://github.com/atlantis-amps/psatlantismodelupdates"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#D9E3E4"
    logo: "https://user-images.githubusercontent.com/11339490/204617034-60925058-5fa4-468c-ad50-6c5719757066.jpg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
      - icon: github
        href: https://github.com/nmfs-opensci
        text: "NMFS OpenSci"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: content/Initial_conditions.qmd
        text: Initial conditions
      - href: content/Parameter_updates_during_calibration.qmd
        text: Calibration
      - href: content/diet.qmd
        text: Diets
      - href: content/KDEP.qmd
        text: Biological parameters
      - href: content/Responses_to_temperature_and_oxygen.qmd
        text: Response to temperature and O2
      - href: content/salmon.qmd
        text: Salmon groups
      - href: content/jellyfishtext.qmd
        text: Jellyfish
      - href: content/residents.qmd
        text: Resident orcas
      - href: content/foodweb.qmd
        text: Foodweb
      - href: content/acknowledgements.qmd
        text: Acknowledgments
      - href: content/Parametrization_contaminant_submodule_PCBs.qmd
        text: PCBs

      


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto


